# Generated by Django 2.2.5 on 2020-02-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machineLearning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstfilter',
            name='entry_date',
        ),
    ]
