# Generated by Django 2.2.5 on 2020-02-13 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('machineLearning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetworkTrainingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField()),
                ('use_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='NeuralNetworkTestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField()),
                ('use_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='NeuralNetworkPredictedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField()),
                ('use_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Employees')),
            ],
        ),
    ]
